//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.SuperSimpleContactList
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Contact.
    /// </summary>
    // *** Start programmer edit section *** (Contact CustomAttributes)

    // *** End programmer edit section *** (Contact CustomAttributes)
    [BusinessServer("NewPlatform.SuperSimpleContactList.ContactBS, SuperSimpleContactList.BusinessServ" +
        "ers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [PublishName("Contact")]
    [AutoAltered()]
    [Caption("Personal contact")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ContactE", new string[] {
            "Name as \'Name\'",
            "Value as \'Value\'"})]
    [View("ContactL", new string[] {
            "Name as \'Name\'",
            "Value as \'Value\'"})]
    public class Contact : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fValue;
        
        // *** Start programmer edit section *** (Contact CustomMembers)

        // *** End programmer edit section *** (Contact CustomMembers)

        
        /// <summary>
        /// Contact name.
        /// </summary>
        // *** Start programmer edit section *** (Contact.Name CustomAttributes)

        // *** End programmer edit section *** (Contact.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Contact.Name Get start)

                // *** End programmer edit section *** (Contact.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Contact.Name Get end)

                // *** End programmer edit section *** (Contact.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.Name Set start)

                // *** End programmer edit section *** (Contact.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Contact.Name Set end)

                // *** End programmer edit section *** (Contact.Name Set end)
            }
        }
        
        /// <summary>
        /// Contact value.
        /// </summary>
        // *** Start programmer edit section *** (Contact.Value CustomAttributes)

        // *** End programmer edit section *** (Contact.Value CustomAttributes)
        [StrLen(255)]
        public virtual string Value
        {
            get
            {
                // *** Start programmer edit section *** (Contact.Value Get start)

                // *** End programmer edit section *** (Contact.Value Get start)
                string result = this.fValue;
                // *** Start programmer edit section *** (Contact.Value Get end)

                // *** End programmer edit section *** (Contact.Value Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contact.Value Set start)

                // *** End programmer edit section *** (Contact.Value Set start)
                this.fValue = value;
                // *** Start programmer edit section *** (Contact.Value Set end)

                // *** End programmer edit section *** (Contact.Value Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ContactE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactE", typeof(NewPlatform.SuperSimpleContactList.Contact));
                }
            }
            
            /// <summary>
            /// "ContactL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactL", typeof(NewPlatform.SuperSimpleContactList.Contact));
                }
            }
        }
    }
}
