import NewPlatformSuperSimpleContactListContactEController from '../new-platform-super-simple-contact-list-contact-e';

var NewPlatformSuperSimpleContactListContactENewController = NewPlatformSuperSimpleContactListContactEController;
export default NewPlatformSuperSimpleContactListContactENewController;
