version: '3'

services:
  app:
    image: supersimplecontactlist/app
    links:
      - app-postgres-db:app-postgres-db
    ports:
      - 80:80

  app-postgres-db:
    image: supersimplecontactlist/postgre-sql
    volumes:
      - DB:/var/lib/pgsql/data/
    ports:
      - 5432:5432
volumes:
  DB:
