//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.SuperSimpleContactList
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Contact BS.
    /// </summary>
    //  *** Start programmer edit section *** (ContactBS CustomAttributes)

    //  *** End programmer edit section *** (ContactBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ContactBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        //  *** Start programmer edit section *** (ContactBS CustomMembers)

        //  *** End programmer edit section *** (ContactBS CustomMembers)

        
        //  *** Start programmer edit section *** (OnUpdateContact CustomAttributes)

        //  *** End programmer edit section *** (OnUpdateContact CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateContact(NewPlatform.SuperSimpleContactList.Contact UpdatedObject)
        {
            //  *** Start programmer edit section *** (OnUpdateContact)
            return new ICSSoft.STORMNET.DataObject[0];
            //  *** End programmer edit section *** (OnUpdateContact)
        }
    }
}
