name: Build-Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: action "Install Dependencies" 
       uses = "nuxt/actions-yarn@node-10"
        args = "install"
   
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v2
#       with:
#         dotnet-version: 3.1
        
#     - name: Restore dependencies
#       run: dotnet restore src/SuperSimpleContactList/ODataBackend/SuperSimpleContactList.ODataBackend.csproj
    
#     - name: Build
#       run: dotnet build --no-restore src/SuperSimpleContactList/ODataBackend/SuperSimpleContactList.ODataBackend.csproj
    
#     - name: Test
#       run: dotnet test --no-build --verbosity normal /src/SuperSimpleContactList/Tests/SuperSimpleContactList.Tests.csproj
