# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  path: src/ember-app
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ember-version: [3.1.4]


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.ember-version }}
      uses: emberjs@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci $path
    - run: npm run build --if-present
    - run: npm test
